/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }

    public static String message(){return "my name is parkkangho";}
}
